trigger:
  - feature/azure-pipelines

pool:
  vmImage: 'ubuntu-16.04'

variables:
  Version.MajorMinor: 1.0
  Version.CounterLabel: $[format('BuildVersion.{0}', variables['Version.MajorMinor'])]
  Version.Revision: $[counter(variables['Version.CounterLabel'], 0)]

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "Build Version is ''${Version.MajorMinor}.${Version.Revision}''."'
