trigger:
  - feature/azure-pipelines

pool:
  vmImage: 'ubuntu-16.04'

variables:
  Version.MajorMinor: 1.0
  Version.Revision: $[counter('BuildVersion.' + variables['Version.MajorMinor'], 0)]

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "Build Version is ''${Version.MajorMinor}.${Version.Revision}''."'
