trigger:
  - feature/azure-pipelines

pool:
  vmImage: 'ubuntu-16.04'

variables:
  Version.Major: 1
  Version.Minor: 0
  Version.MajorMinor: $[format('{0}.{1}', variables['Version.Major'], variables['Version.Minor'])]
  Version.Revision: $[counter(format('BuildVersion.{0}', variables['Version.MajorMinor']), 0)]

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "Build Version is ''${VERSION_MAJORMINOR}.${VERSION_REVISION}''."'
